---

- name: Prune Docker containers
  docker_prune:
    containers: yes
    images: yes
    images_filters:
      dangling: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Log into Dockerhub
  docker_login:
    username: "{{ dockerhub_user }}"
    password: "{{ dockerhub_password }}"
    reauthorize: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3